### ISSUE TITLE
Some API's endpoints Does not work

### ISSUE THREAD

**Issue by saaadol** [hu8813/pong42#1]
Hello, I've tested some api endpoints and there is an error for multiple ones : 
1. api/ping/ 
2. api/login/
The issue is when this endpoints are requested, you return a Python error as JSON response :  "{"error": "cannot access local variable 'e' where it is not associated with a value"}" 
**Solution** : 
In login_view() located in backend/myapp/views.py path, Line 1106, you are returning str(e) by  using `else` statement, knowing that e will only work inside an `except` statement, and in that special case, it's not really an error because user is just using GET request rather then POST, so I suggest you use a custom method message instead of e.

**Comment by hu8813** [comment]
Thank you so much. Will check it.
